
worker_processes 1;

events {

    worker_connections 512;
    multi_accept on;
}


http {
include /etc/nginx/mime.types;
server {
    listen 80;
    server_name django_test;

    location /static/ {


        alias /stat/staticfile/;
        include /etc/nginx/mime.types;

    }


    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://django_test:8000;
    }


}
}